spring.application.name=ecom-application
spring.h2.console.enabled=true

# H2 database setup
#spring.datasource.url=jdbc:h2:mem:test

# PostgreSQL database setup
spring.datasource.url=jdbc:postgresql://localhost:5432/ecom-database
spring.datasource.username=haoxugt
spring.datasource.password=haoxugt

spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Expose Actuator Endpoints
management.endpoints.web.exposure.include=beans,health
management.endpoint.health.show-details=always
#management.endpoint.shutdown.enabled=true
management.info.env.enabled=true
info.app.name=ecom
info.app.description=App built by us
info.app.version=2

